var apiCountries = [
  {"iso_3166_1": "AD", "en_us": "Andorra", "ar_sa": "أندورا"},
  {
    "iso_3166_1": "AE",
    "en_us": "United Arab Emirates",
    "ar_sa": "الإمارات العربية المتحدة"
  },
  {"iso_3166_1": "AF", "en_us": "Afghanistan", "ar_sa": "أفغانستان"},
  {
    "iso_3166_1": "AG",
    "en_us": "Antigua and Barbuda",
    "ar_sa": "أنتيغوا وبربودا"
  },
  {"iso_3166_1": "AI", "en_us": "Anguilla", "ar_sa": "أنغويلا"},
  {"iso_3166_1": "AL", "en_us": "Albania", "ar_sa": "ألبانيا"},
  {"iso_3166_1": "AM", "en_us": "Armenia", "ar_sa": "أرمينيا"},
  {
    "iso_3166_1": "AN",
    "en_us": "Netherlands Antilles",
    "ar_sa": "جزر الأنتيل الهولندية"
  },
  {"iso_3166_1": "AO", "en_us": "Angola", "ar_sa": "أنغولا"},
  {"iso_3166_1": "AQ", "en_us": "Antarctica", "ar_sa": "أنتاركتيكا"},
  {"iso_3166_1": "AR", "en_us": "Argentina", "ar_sa": "الأرجنتين"},
  {"iso_3166_1": "AS", "en_us": "American Samoa", "ar_sa": "ساموا الأمريكية"},
  {"iso_3166_1": "AT", "en_us": "Austria", "ar_sa": "النمسا"},
  {"iso_3166_1": "AU", "en_us": "Australia", "ar_sa": "أستراليا"},
  {"iso_3166_1": "AW", "en_us": "Aruba", "ar_sa": "آروبا"},
  {"iso_3166_1": "AZ", "en_us": "Azerbaijan", "ar_sa": "أذربيجان"},
  {
    "iso_3166_1": "BA",
    "en_us": "Bosnia and Herzegovina",
    "ar_sa": "البوسنة والهرسك"
  },
  {"iso_3166_1": "BB", "en_us": "Barbados", "ar_sa": "بربادوس"},
  {"iso_3166_1": "BD", "en_us": "Bangladesh", "ar_sa": "بنجلاديش"},
  {"iso_3166_1": "BE", "en_us": "Belgium", "ar_sa": "بلجيكا"},
  {"iso_3166_1": "BF", "en_us": "Burkina Faso", "ar_sa": "بوركينا فاسو"},
  {"iso_3166_1": "BG", "en_us": "Bulgaria", "ar_sa": "بلغاريا"},
  {"iso_3166_1": "BH", "en_us": "Bahrain", "ar_sa": "البحرين"},
  {"iso_3166_1": "BI", "en_us": "Burundi", "ar_sa": "بوروندي"},
  {"iso_3166_1": "BJ", "en_us": "Benin", "ar_sa": "بنين"},
  {"iso_3166_1": "BM", "en_us": "Bermuda", "ar_sa": "برمودا"},
  {"iso_3166_1": "BN", "en_us": "Brunei Darussalam", "ar_sa": "بروناي"},
  {"iso_3166_1": "BO", "en_us": "Bolivia", "ar_sa": "بوليفيا"},
  {"iso_3166_1": "BR", "en_us": "Brazil", "ar_sa": "البرازيل"},
  {"iso_3166_1": "BS", "en_us": "Bahamas", "ar_sa": "الباهاما"},
  {"iso_3166_1": "BT", "en_us": "Bhutan", "ar_sa": "بوتان"},
  {"iso_3166_1": "BU", "en_us": "Burma", "ar_sa": "Burma"},
  {"iso_3166_1": "BV", "en_us": "Bouvet Island", "ar_sa": "جزيرة بوفيه"},
  {"iso_3166_1": "BW", "en_us": "Botswana", "ar_sa": "بتسوانا"},
  {"iso_3166_1": "BY", "en_us": "Belarus", "ar_sa": "روسيا البيضاء"},
  {"iso_3166_1": "BZ", "en_us": "Belize", "ar_sa": "بليز"},
  {"iso_3166_1": "CA", "en_us": "Canada", "ar_sa": "كندا"},
  {"iso_3166_1": "CC", "en_us": "Cocos  Islands", "ar_sa": "جزر كوكوس"},
  {"iso_3166_1": "CD", "en_us": "Congo", "ar_sa": "الكونغو - كينشاسا"},
  {
    "iso_3166_1": "CF",
    "en_us": "Central African Republic",
    "ar_sa": "جمهورية أفريقيا الوسطى"
  },
  {"iso_3166_1": "CG", "en_us": "Congo", "ar_sa": "الكونغو - برازافيل"},
  {"iso_3166_1": "CH", "en_us": "Switzerland", "ar_sa": "سويسرا"},
  {"iso_3166_1": "CI", "en_us": "Cote D'Ivoire", "ar_sa": "ساحل العاج"},
  {"iso_3166_1": "CK", "en_us": "Cook Islands", "ar_sa": "جزر كوك"},
  {"iso_3166_1": "CL", "en_us": "Chile", "ar_sa": "شيلي"},
  {"iso_3166_1": "CM", "en_us": "Cameroon", "ar_sa": "الكاميرون"},
  {"iso_3166_1": "CN", "en_us": "China", "ar_sa": "الصين"},
  {"iso_3166_1": "CO", "en_us": "Colombia", "ar_sa": "كولومبيا"},
  {"iso_3166_1": "CR", "en_us": "Costa Rica", "ar_sa": "كوستاريكا"},
  {
    "iso_3166_1": "CS",
    "en_us": "Serbia and Montenegro",
    "ar_sa": "Serbia and Montenegro"
  },
  {"iso_3166_1": "CU", "en_us": "Cuba", "ar_sa": "كوبا"},
  {"iso_3166_1": "CV", "en_us": "Cape Verde", "ar_sa": "الرأس الأخضر"},
  {"iso_3166_1": "CX", "en_us": "Christmas Island", "ar_sa": "جزيرة الكريسماس"},
  {"iso_3166_1": "CY", "en_us": "Cyprus", "ar_sa": "قبرص"},
  {"iso_3166_1": "CZ", "en_us": "Czech Republic", "ar_sa": "جمهورية التشيك"},
  {"iso_3166_1": "DE", "en_us": "Germany", "ar_sa": "ألمانيا"},
  {"iso_3166_1": "DJ", "en_us": "Djibouti", "ar_sa": "جيبوتي"},
  {"iso_3166_1": "DK", "en_us": "Denmark", "ar_sa": "الدانمرك"},
  {"iso_3166_1": "DM", "en_us": "Dominica", "ar_sa": "دومينيكا"},
  {
    "iso_3166_1": "DO",
    "en_us": "Dominican Republic",
    "ar_sa": "جمهورية الدومينيك"
  },
  {"iso_3166_1": "DZ", "en_us": "Algeria", "ar_sa": "الجزائر"},
  {"iso_3166_1": "EC", "en_us": "Ecuador", "ar_sa": "الإكوادور"},
  {"iso_3166_1": "EE", "en_us": "Estonia", "ar_sa": "أستونيا"},
  {"iso_3166_1": "EG", "en_us": "Egypt", "ar_sa": "مصر"},
  {"iso_3166_1": "EH", "en_us": "Western Sahara", "ar_sa": "الصحراء الغربية"},
  {"iso_3166_1": "ER", "en_us": "Eritrea", "ar_sa": "أريتريا"},
  {"iso_3166_1": "ES", "en_us": "Spain", "ar_sa": "إسبانيا"},
  {"iso_3166_1": "ET", "en_us": "Ethiopia", "ar_sa": "إثيوبيا"},
  {"iso_3166_1": "FI", "en_us": "Finland", "ar_sa": "فنلندا"},
  {"iso_3166_1": "FJ", "en_us": "Fiji", "ar_sa": "فيجي"},
  {"iso_3166_1": "FK", "en_us": "Falkland Islands", "ar_sa": "جزر فوكلاند"},
  {"iso_3166_1": "FM", "en_us": "Micronesia", "ar_sa": "ميكرونيزيا"},
  {"iso_3166_1": "FO", "en_us": "Faeroe Islands", "ar_sa": "جزر فارو"},
  {"iso_3166_1": "FR", "en_us": "France", "ar_sa": "فرنسا"},
  {"iso_3166_1": "GA", "en_us": "Gabon", "ar_sa": "الجابون"},
  {"iso_3166_1": "GB", "en_us": "United Kingdom", "ar_sa": "المملكة المتحدة"},
  {"iso_3166_1": "GD", "en_us": "Grenada", "ar_sa": "غرينادا"},
  {"iso_3166_1": "GE", "en_us": "Georgia", "ar_sa": "جورجيا"},
  {"iso_3166_1": "GF", "en_us": "French Guiana", "ar_sa": "غويانا الفرنسية"},
  {"iso_3166_1": "GH", "en_us": "Ghana", "ar_sa": "غانا"},
  {"iso_3166_1": "GI", "en_us": "Gibraltar", "ar_sa": "جبل طارق"},
  {"iso_3166_1": "GL", "en_us": "Greenland", "ar_sa": "غرينلاند"},
  {"iso_3166_1": "GM", "en_us": "Gambia", "ar_sa": "غامبيا"},
  {"iso_3166_1": "GN", "en_us": "Guinea", "ar_sa": "غينيا"},
  {"iso_3166_1": "GP", "en_us": "Guadaloupe", "ar_sa": "جوادلوب"},
  {
    "iso_3166_1": "GQ",
    "en_us": "Equatorial Guinea",
    "ar_sa": "غينيا الاستوائية"
  },
  {"iso_3166_1": "GR", "en_us": "Greece", "ar_sa": "اليونان"},
  {
    "iso_3166_1": "GS",
    "en_us": "South Georgia and the South Sandwich Islands",
    "ar_sa": "جورجيا الجنوبية وجزر ساندويتش الجنوبية"
  },
  {"iso_3166_1": "GT", "en_us": "Guatemala", "ar_sa": "غواتيمالا"},
  {"iso_3166_1": "GU", "en_us": "Guam", "ar_sa": "غوام"},
  {"iso_3166_1": "GW", "en_us": "Guinea-Bissau", "ar_sa": "غينيا بيساو"},
  {"iso_3166_1": "GY", "en_us": "Guyana", "ar_sa": "غيانا"},
  {"iso_3166_1": "HK", "en_us": "Hong Kong", "ar_sa": "هونغ كونغ الصينية"},
  {
    "iso_3166_1": "HM",
    "en_us": "Heard and McDonald Islands",
    "ar_sa": "جزيرة هيرد وجزر ماكدونالد"
  },
  {"iso_3166_1": "HN", "en_us": "Honduras", "ar_sa": "هندوراس"},
  {"iso_3166_1": "HR", "en_us": "Croatia", "ar_sa": "كرواتيا"},
  {"iso_3166_1": "HT", "en_us": "Haiti", "ar_sa": "هايتي"},
  {"iso_3166_1": "HU", "en_us": "Hungary", "ar_sa": "هنغاريا"},
  {"iso_3166_1": "ID", "en_us": "Indonesia", "ar_sa": "إندونيسيا"},
  {"iso_3166_1": "IE", "en_us": "Ireland", "ar_sa": "أيرلندا"},
  {"iso_3166_1": "IL", "en_us": "Israel", "ar_sa": "إسرائيل"},
  {"iso_3166_1": "IN", "en_us": "India", "ar_sa": "الهند"},
  {
    "iso_3166_1": "IO",
    "en_us": "British Indian Ocean Territory",
    "ar_sa": "الإقليم البريطاني في المحيط الهندي"
  },
  {"iso_3166_1": "IQ", "en_us": "Iraq", "ar_sa": "العراق"},
  {"iso_3166_1": "IR", "en_us": "Iran", "ar_sa": "إيران"},
  {"iso_3166_1": "IS", "en_us": "Iceland", "ar_sa": "أيسلندا"},
  {"iso_3166_1": "IT", "en_us": "Italy", "ar_sa": "إيطاليا"},
  {"iso_3166_1": "JM", "en_us": "Jamaica", "ar_sa": "جامايكا"},
  {"iso_3166_1": "JO", "en_us": "Jordan", "ar_sa": "الأردن"},
  {"iso_3166_1": "JP", "en_us": "Japan", "ar_sa": "اليابان"},
  {"iso_3166_1": "KE", "en_us": "Kenya", "ar_sa": "كينيا"},
  {"iso_3166_1": "KG", "en_us": "Kyrgyz Republic", "ar_sa": "قرغيزستان"},
  {"iso_3166_1": "KH", "en_us": "Cambodia", "ar_sa": "كمبوديا"},
  {"iso_3166_1": "KI", "en_us": "Kiribati", "ar_sa": "كيريباتي"},
  {"iso_3166_1": "KM", "en_us": "Comoros", "ar_sa": "جزر القمر"},
  {
    "iso_3166_1": "KN",
    "en_us": "St. Kitts and Nevis",
    "ar_sa": "سانت كيتس ونيفيس"
  },
  {"iso_3166_1": "KP", "en_us": "North Korea", "ar_sa": "كوريا الشمالية"},
  {"iso_3166_1": "KR", "en_us": "South Korea", "ar_sa": "كوريا الجنوبية"},
  {"iso_3166_1": "KW", "en_us": "Kuwait", "ar_sa": "الكويت"},
  {"iso_3166_1": "KY", "en_us": "Cayman Islands", "ar_sa": "جزر الكايمن"},
  {"iso_3166_1": "KZ", "en_us": "Kazakhstan", "ar_sa": "كازاخستان"},
  {
    "iso_3166_1": "LA",
    "en_us": "Lao People's Democratic Republic",
    "ar_sa": "لاوس"
  },
  {"iso_3166_1": "LB", "en_us": "Lebanon", "ar_sa": "لبنان"},
  {"iso_3166_1": "LC", "en_us": "St. Lucia", "ar_sa": "سانت لوسيا"},
  {"iso_3166_1": "LI", "en_us": "Liechtenstein", "ar_sa": "ليختنشتاين"},
  {"iso_3166_1": "LK", "en_us": "Sri Lanka", "ar_sa": "سريلانكا"},
  {"iso_3166_1": "LR", "en_us": "Liberia", "ar_sa": "ليبيريا"},
  {"iso_3166_1": "LS", "en_us": "Lesotho", "ar_sa": "ليسوتو"},
  {"iso_3166_1": "LT", "en_us": "Lithuania", "ar_sa": "ليتوانيا"},
  {"iso_3166_1": "LU", "en_us": "Luxembourg", "ar_sa": "لوكسمبورغ"},
  {"iso_3166_1": "LV", "en_us": "Latvia", "ar_sa": "لاتفيا"},
  {"iso_3166_1": "LY", "en_us": "Libyan Arab Jamahiriya", "ar_sa": "ليبيا"},
  {"iso_3166_1": "MA", "en_us": "Morocco", "ar_sa": "المغرب"},
  {"iso_3166_1": "MC", "en_us": "Monaco", "ar_sa": "موناكو"},
  {"iso_3166_1": "MD", "en_us": "Moldova", "ar_sa": "مولدافيا"},
  {"iso_3166_1": "ME", "en_us": "Montenegro", "ar_sa": "الجبل الأسود"},
  {"iso_3166_1": "MG", "en_us": "Madagascar", "ar_sa": "مدغشقر"},
  {"iso_3166_1": "MH", "en_us": "Marshall Islands", "ar_sa": "جزر المارشال"},
  {"iso_3166_1": "MK", "en_us": "Macedonia", "ar_sa": "مقدونيا"},
  {"iso_3166_1": "ML", "en_us": "Mali", "ar_sa": "مالي"},
  {"iso_3166_1": "MM", "en_us": "Myanmar", "ar_sa": "ميانمار -بورما"},
  {"iso_3166_1": "MN", "en_us": "Mongolia", "ar_sa": "منغوليا"},
  {
    "iso_3166_1": "MO",
    "en_us": "Macao",
    "ar_sa": "مكاو الصينية (منطقة إدارية خاصة)"
  },
  {
    "iso_3166_1": "MP",
    "en_us": "Northern Mariana Islands",
    "ar_sa": "جزر ماريانا الشمالية"
  },
  {"iso_3166_1": "MQ", "en_us": "Martinique", "ar_sa": "مارتينيك"},
  {"iso_3166_1": "MR", "en_us": "Mauritania", "ar_sa": "موريتانيا"},
  {"iso_3166_1": "MS", "en_us": "Montserrat", "ar_sa": "مونتسرات"},
  {"iso_3166_1": "MT", "en_us": "Malta", "ar_sa": "مالطا"},
  {"iso_3166_1": "MU", "en_us": "Mauritius", "ar_sa": "موريشيوس"},
  {"iso_3166_1": "MV", "en_us": "Maldives", "ar_sa": "جزر المالديف"},
  {"iso_3166_1": "MW", "en_us": "Malawi", "ar_sa": "ملاوي"},
  {"iso_3166_1": "MX", "en_us": "Mexico", "ar_sa": "المكسيك"},
  {"iso_3166_1": "MY", "en_us": "Malaysia", "ar_sa": "ماليزيا"},
  {"iso_3166_1": "MZ", "en_us": "Mozambique", "ar_sa": "موزمبيق"},
  {"iso_3166_1": "NA", "en_us": "Namibia", "ar_sa": "ناميبيا"},
  {"iso_3166_1": "NC", "en_us": "New Caledonia", "ar_sa": "كاليدونيا الجديدة"},
  {"iso_3166_1": "NE", "en_us": "Niger", "ar_sa": "النيجر"},
  {"iso_3166_1": "NF", "en_us": "Norfolk Island", "ar_sa": "جزيرة نورفوك"},
  {"iso_3166_1": "NG", "en_us": "Nigeria", "ar_sa": "نيجيريا"},
  {"iso_3166_1": "NI", "en_us": "Nicaragua", "ar_sa": "نيكاراغوا"},
  {"iso_3166_1": "NL", "en_us": "Netherlands", "ar_sa": "هولندا"},
  {"iso_3166_1": "NO", "en_us": "Norway", "ar_sa": "النرويج"},
  {"iso_3166_1": "NP", "en_us": "Nepal", "ar_sa": "نيبال"},
  {"iso_3166_1": "NR", "en_us": "Nauru", "ar_sa": "ناورو"},
  {"iso_3166_1": "NU", "en_us": "Niue", "ar_sa": "نيوي"},
  {"iso_3166_1": "NZ", "en_us": "New Zealand", "ar_sa": "نيوزيلاندا"},
  {"iso_3166_1": "OM", "en_us": "Oman", "ar_sa": "عُمان"},
  {"iso_3166_1": "PA", "en_us": "Panama", "ar_sa": "بنما"},
  {"iso_3166_1": "PE", "en_us": "Peru", "ar_sa": "بيرو"},
  {
    "iso_3166_1": "PF",
    "en_us": "French Polynesia",
    "ar_sa": "بولينيزيا الفرنسية"
  },
  {
    "iso_3166_1": "PG",
    "en_us": "Papua New Guinea",
    "ar_sa": "بابوا غينيا الجديدة"
  },
  {"iso_3166_1": "PH", "en_us": "Philippines", "ar_sa": "الفلبين"},
  {"iso_3166_1": "PK", "en_us": "Pakistan", "ar_sa": "باكستان"},
  {"iso_3166_1": "PL", "en_us": "Poland", "ar_sa": "بولندا"},
  {
    "iso_3166_1": "PM",
    "en_us": "St. Pierre and Miquelon",
    "ar_sa": "سانت بيير وميكولون"
  },
  {"iso_3166_1": "PN", "en_us": "Pitcairn Island", "ar_sa": "جزر بيتكيرن"},
  {"iso_3166_1": "PR", "en_us": "Puerto Rico", "ar_sa": "بورتوريكو"},
  {
    "iso_3166_1": "PS",
    "en_us": "Palestinian Territory",
    "ar_sa": "الأراضي الفلسطينية"
  },
  {"iso_3166_1": "PT", "en_us": "Portugal", "ar_sa": "البرتغال"},
  {"iso_3166_1": "PW", "en_us": "Palau", "ar_sa": "بالاو"},
  {"iso_3166_1": "PY", "en_us": "Paraguay", "ar_sa": "باراغواي"},
  {"iso_3166_1": "QA", "en_us": "Qatar", "ar_sa": "قطر"},
  {"iso_3166_1": "RE", "en_us": "Reunion", "ar_sa": "روينيون"},
  {"iso_3166_1": "RO", "en_us": "Romania", "ar_sa": "رومانيا"},
  {"iso_3166_1": "RS", "en_us": "Serbia", "ar_sa": "صربيا"},
  {"iso_3166_1": "RU", "en_us": "Russia", "ar_sa": "روسيا"},
  {"iso_3166_1": "RW", "en_us": "Rwanda", "ar_sa": "رواندا"},
  {
    "iso_3166_1": "SA",
    "en_us": "Saudi Arabia",
    "ar_sa": "المملكة العربية السعودية"
  },
  {"iso_3166_1": "SB", "en_us": "Solomon Islands", "ar_sa": "جزر سليمان"},
  {"iso_3166_1": "SC", "en_us": "Seychelles", "ar_sa": "سيشل"},
  {"iso_3166_1": "SD", "en_us": "Sudan", "ar_sa": "السودان"},
  {"iso_3166_1": "SE", "en_us": "Sweden", "ar_sa": "السويد"},
  {"iso_3166_1": "SG", "en_us": "Singapore", "ar_sa": "سنغافورة"},
  {"iso_3166_1": "SH", "en_us": "St. Helena", "ar_sa": "سانت هيلنا"},
  {"iso_3166_1": "SI", "en_us": "Slovenia", "ar_sa": "سلوفينيا"},
  {
    "iso_3166_1": "SJ",
    "en_us": "Svalbard & Jan Mayen Islands",
    "ar_sa": "سفالبارد وجان مايان"
  },
  {"iso_3166_1": "SK", "en_us": "Slovakia", "ar_sa": "سلوفاكيا"},
  {"iso_3166_1": "SL", "en_us": "Sierra Leone", "ar_sa": "سيراليون"},
  {"iso_3166_1": "SM", "en_us": "San Marino", "ar_sa": "سان مارينو"},
  {"iso_3166_1": "SN", "en_us": "Senegal", "ar_sa": "السنغال"},
  {"iso_3166_1": "SO", "en_us": "Somalia", "ar_sa": "الصومال"},
  {"iso_3166_1": "SR", "en_us": "Suriname", "ar_sa": "سورينام"},
  {"iso_3166_1": "SS", "en_us": "South Sudan", "ar_sa": "جنوب السودان"},
  {
    "iso_3166_1": "ST",
    "en_us": "Sao Tome and Principe",
    "ar_sa": "ساو تومي وبرينسيبي"
  },
  {"iso_3166_1": "SU", "en_us": "Soviet Union", "ar_sa": "Soviet Union"},
  {"iso_3166_1": "SV", "en_us": "El Salvador", "ar_sa": "السلفادور"},
  {"iso_3166_1": "SY", "en_us": "Syrian Arab Republic", "ar_sa": "سوريا"},
  {"iso_3166_1": "SZ", "en_us": "Swaziland", "ar_sa": "سوازيلاند"},
  {
    "iso_3166_1": "TC",
    "en_us": "Turks and Caicos Islands",
    "ar_sa": "جزر الترك وجايكوس"
  },
  {"iso_3166_1": "TD", "en_us": "Chad", "ar_sa": "تشاد"},
  {
    "iso_3166_1": "TF",
    "en_us": "French Southern Territories",
    "ar_sa": "المقاطعات الجنوبية الفرنسية"
  },
  {"iso_3166_1": "TG", "en_us": "Togo", "ar_sa": "توجو"},
  {"iso_3166_1": "TH", "en_us": "Thailand", "ar_sa": "تايلاند"},
  {"iso_3166_1": "TJ", "en_us": "Tajikistan", "ar_sa": "طاجكستان"},
  {"iso_3166_1": "TK", "en_us": "Tokelau", "ar_sa": "توكيلو"},
  {"iso_3166_1": "TL", "en_us": "Timor-Leste", "ar_sa": "تيمور الشرقية"},
  {"iso_3166_1": "TM", "en_us": "Turkmenistan", "ar_sa": "تركمانستان"},
  {"iso_3166_1": "TN", "en_us": "Tunisia", "ar_sa": "تونس"},
  {"iso_3166_1": "TO", "en_us": "Tonga", "ar_sa": "تونغا"},
  {"iso_3166_1": "TP", "en_us": "East Timor", "ar_sa": "East Timor"},
  {"iso_3166_1": "TR", "en_us": "Turkey", "ar_sa": "تركيا"},
  {
    "iso_3166_1": "TT",
    "en_us": "Trinidad and Tobago",
    "ar_sa": "ترينيداد وتوباغو"
  },
  {"iso_3166_1": "TV", "en_us": "Tuvalu", "ar_sa": "توفالو"},
  {"iso_3166_1": "TW", "en_us": "Taiwan", "ar_sa": "تايوان"},
  {"iso_3166_1": "TZ", "en_us": "Tanzania", "ar_sa": "تانزانيا"},
  {"iso_3166_1": "UA", "en_us": "Ukraine", "ar_sa": "أوكرانيا"},
  {"iso_3166_1": "UG", "en_us": "Uganda", "ar_sa": "أوغندا"},
  {
    "iso_3166_1": "UM",
    "en_us": "United States Minor Outlying Islands",
    "ar_sa": "جزر الولايات المتحدة النائية"
  },
  {
    "iso_3166_1": "US",
    "en_us": "United States of America",
    "ar_sa": "الولايات المتحدة"
  },
  {"iso_3166_1": "UY", "en_us": "Uruguay", "ar_sa": "أورغواي"},
  {"iso_3166_1": "UZ", "en_us": "Uzbekistan", "ar_sa": "أوزبكستان"},
  {"iso_3166_1": "VA", "en_us": "Holy See", "ar_sa": "الفاتيكان"},
  {
    "iso_3166_1": "VC",
    "en_us": "St. Vincent and the Grenadines",
    "ar_sa": "سانت فنسنت وغرنادين"
  },
  {"iso_3166_1": "VE", "en_us": "Venezuela", "ar_sa": "فنزويلا"},
  {
    "iso_3166_1": "VG",
    "en_us": "British Virgin Islands",
    "ar_sa": "جزر فرجين البريطانية"
  },
  {
    "iso_3166_1": "VI",
    "en_us": "US Virgin Islands",
    "ar_sa": "جزر فرجين الأمريكية"
  },
  {"iso_3166_1": "VN", "en_us": "Vietnam", "ar_sa": "فيتنام"},
  {"iso_3166_1": "VU", "en_us": "Vanuatu", "ar_sa": "فانواتو"},
  {
    "iso_3166_1": "WF",
    "en_us": "Wallis and Futuna Islands",
    "ar_sa": "جزر والس وفوتونا"
  },
  {"iso_3166_1": "WS", "en_us": "Samoa", "ar_sa": "ساموا"},
  {"iso_3166_1": "XC", "en_us": "Czechoslovakia", "ar_sa": "Czechoslovakia"},
  {"iso_3166_1": "XG", "en_us": "East Germany", "ar_sa": "East Germany"},
  {
    "iso_3166_1": "XI",
    "en_us": "Northern Ireland",
    "ar_sa": "Northern Ireland"
  },
  {"iso_3166_1": "XK", "en_us": "Kosovo", "ar_sa": "كوسوفو"},
  {"iso_3166_1": "YE", "en_us": "Yemen", "ar_sa": "اليمن"},
  {"iso_3166_1": "YT", "en_us": "Mayotte", "ar_sa": "مايوت"},
  {"iso_3166_1": "YU", "en_us": "Yugoslavia", "ar_sa": "Yugoslavia"},
  {"iso_3166_1": "ZA", "en_us": "South Africa", "ar_sa": "جنوب أفريقيا"},
  {"iso_3166_1": "ZM", "en_us": "Zambia", "ar_sa": "زامبيا"},
  {"iso_3166_1": "ZR", "en_us": "Zaire", "ar_sa": "Zaire"},
  {"iso_3166_1": "ZW", "en_us": "Zimbabwe", "ar_sa": "زيمبابوي"}
];
