var genresList = [
  {"id": 28, "en_us": "Action", 'ar_sa': 'حركة'},
  {"id": 12, "en_us": "Adventure", 'ar_sa': 'مغامرة'},
  {"id": 16, "en_us": "Animation", 'ar_sa': 'رسوم متحركة'},
  {"id": 35, "en_us": "Comedy", 'ar_sa': 'كوميديا'},
  {"id": 80, "en_us": "Crime", 'ar_sa': 'جريمة'},
  {"id": 99, "en_us": "Documentary", 'ar_sa': 'وثائقي'},
  {"id": 18, "en_us": "Drama", 'ar_sa': 'دراما'},
  {"id": 10751, "en_us": "Family", 'ar_sa': 'عائلي'},
  {"id": 14, "en_us": "Fantasy", 'ar_sa': 'فانتازيا'},
  {"id": 36, "en_us": "History", 'ar_sa': 'تاريخ'},
  {"id": 27, "en_us": "Horror", 'ar_sa': 'رعب'},
  {"id": 10402, "en_us": "Music", 'ar_sa': 'موسيقى'},
  {"id": 9648, "en_us": "Mystery", 'ar_sa': 'غموض'},
  {"id": 10749, "en_us": "Romance", 'ar_sa': 'رومنسية'},
  {"id": 878, "en_us": "Science Fiction", 'ar_sa': 'خيال علمي'},
  {"id": 53, "en_us": "Thriller", 'ar_sa': 'إثارة'},
  {"id": 10752, "en_us": "War", 'ar_sa': 'حرب'},
  {"id": 37, "en_us": "Western", 'ar_sa': 'غربي'},
  {"id": 10759, "en_us": "Action & Adventure", 'ar_sa': 'حركة ومغامرة'},
  {"id": 10762, "en_us": "Kids", 'ar_sa': 'أطفال'},
  {"id": 10763, "en_us": "News", 'ar_sa': 'أخبار'},
  {"id": 10764, "en_us": "Reality", 'ar_sa': 'واقع'},
  {"id": 10765, "en_us": "Sci-Fi & Fantasy", 'ar_sa': 'خيال علمي وفانتازيا'},
  {"id": 10766, "en_us": "Soap", 'ar_sa': 'أوبرا صابونية'},
  {"id": 10767, "en_us": "Talk", 'ar_sa': 'حوار'},
  {"id": 10768, "en_us": "War & Politics", 'ar_sa': 'حرب وسياسة'},
];
